### PR TITLE
Fix PingWorker

### LINKED ISSUE #502: PingWorker not work
Work [ id=42e1814b-15be-45aa-9fba-293602b236b0, tags={ info.mqtt.android.service.ping.PingWorker } ] was cancelled
                 java.util.concurrent.CancellationException: Task was cancelled.
                 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
                 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
                 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
                 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                 	at java.lang.Thread.run(Thread.java:1012)

### LINKED ISSUE #786: Work [ id=35ae198a-e62b-4c0f-8a66-1987e64b8951, tags={ info.mqtt.android.service.ping.PingWorker } ] was cancelled                  androidx.work.impl.WorkerStoppedException
this error comes sometime when greater then 1000 message per second on same time how to fix?

### PR DESCRIPTION
**Pull request by hannesa2**
Based on https://github.com/hannesa2/paho.mqtt.android/issues/502\#issuecomment-2829050918

close #502
close #786

### CODE REVIEW

File: serviceLibrary/src/main/java/info/mqtt/android/service/ping/AlarmPingSender.kt [hunk 1]
```diff
@@ -53,21 +53,31 @@ internal class AlarmPingSender(
...
+        // Only schedule if no work exists or all existing work is finished/cancelled
+        if (workInfo.isEmpty() || workInfo.all { it.state.isFinished }) {
+            val pingWork = OneTimeWorkRequest.Builder(PingWorker::class.java)
+            val data = Data.Builder()
+            data.putBoolean("logging", pingLogging)
+            data.putInt("keepRecordCount", keepPingRecords)
+            data.putString("id", id)
+
+            pingWork
+                .setInitialDelay(30, TimeUnit.SECONDS)
```
Comment (hannesa2) [inline serviceLibrary/src/main/java/info/mqtt/android/service/ping/AlarmPingSender.kt:68]: @minhdangoz May I ask, why you use 30 seconds for `setInitialDelay` instead of given millis ?

image

**Comment by hannesa2** [comment]
This is a better visualization to see what's changed 
image

File: serviceLibrary/src/main/java/info/mqtt/android/service/ping/AlarmPingSender.kt (hunk 1 above)
Comment (hannesa2) [reply serviceLibrary/src/main/java/info/mqtt/android/service/ping/AlarmPingSender.kt]: Without an answer, I revert this
@minhdangoz
